"""empty message

Revision ID: 83341edb6f9b
Revises: 33d38aaa26b3
Create Date: 2021-01-24 00:53:21.345484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83341edb6f9b'
down_revision = '33d38aaa26b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'genres')
    op.create_table('venue_genre_table',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='venue_genre_table_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='venue_genre_table_venue_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id', name='venue_genre_table_pkey')
    )
    op.create_table('artist_genre_table',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='artist_genre_table_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='artist_genre_table_genre_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id', name='artist_genre_table_pkey')
    )
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='genre_pkey')
    )
    op.drop_table('genres')
    # ### end Alembic commands ###
