"""empty message

Revision ID: ed4207b7271a
Revises: e045ce5b8132
Create Date: 2021-01-23 16:00:50.405312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4207b7271a'
down_revision = 'e045ce5b8132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue_description', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent_description', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'seeking_talent_description')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'seeking_venue_description')
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
