"""empty message

Revision ID: fbd9b4bdc653
Revises: ecc3b5910fdf
Create Date: 2021-01-26 18:21:32.265077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd9b4bdc653'
down_revision = 'ecc3b5910fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
